#Source: https://dev.to/aixart/simplifying-deployment-using-github-actions-and-ssh-for-quick-and-easy-updates-284j
name:  Start Friday
# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - nodeDemo
jobs:
  deploy:
    runs-on: ubuntu-latest # Run this job on the latest Ubuntu version

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Check out your repository code

      - name: Start Friday
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file

          # Establish an SSH connection and execute commands on the remote server
          ssh -o StrictHostKeyChecking=no -i private_key.pem rebel@32.72.79.26 <<EOF  #CHANGE
            # Here Document, allows for multiple commands (like a script)
            pkill node #in case the website is currently running
            cd Friday #go to repo
            git pull #update repo
            node app.mjs& #start the updated app
          EOF

          rm -f private_key.pem # Remove the private key file after use for security
    permissions:
      contents: read
      actions: write
      id-token: write
